export const GET_TASK = 'GET_TASK';
export const REQUEST_GET_TASK_SUCCESS = 'REQUEST_GET_TASK_SUCCESS';
export const REQUEST_GET_TASK_FAILED = 'REQUEST_GET_TASK_FAILED';

export const ADD_TASK = 'ADD_TASK';
export const REQUEST_ADD_TASK_SUCCESS = 'REQUEST_ADD_TASK_SUCCESS';
export const REQUEST_ADD_TASK_FAILED = 'REQUEST_ADD_TASK_FAILED';

export const DELETE_TASK = 'DELETE_TASK';
export const REQUEST_DELETE_TASK_SUCCESS = 'REQUEST_DELETE_TASK_SUCCESS';
export const REQUEST_DELETE_TASK_FAILED = 'REQUEST_DELETE_TASK_FAILED';

export const COMPLETE_TASK = 'COMPLETE_TASK';
export const REQUEST_COMPLETE_TASK_SUCCESS = 'REQUEST_COMPLETE_TASK_SUCCESS';
export const REQUEST_COMPLETE_TASK_FAILED = 'REQUEST_COMPLETE_TASK_FAILED';
